server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nike?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    username: root
    password: 123456   # IDEA内置MySQL默认密码
    driver-class-name: com.mysql.cj.jdbc.Driver

  devtools:
    restart:
      enabled: true # 配置热部署
      additional-paths: src/main/java
      exclude: WEB-INF/**

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false

  mvc:
    static-path-pattern: /**

  web:
    resources:
      static-locations: classpath:/static/

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

# 文件上传路径配置
upload:
  path: ${user.dir}/uploads

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate: INFO
    com.example: DEBUG

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: jzh.entity